#!/bin/ash

mkdir /oldrun
mount -n --move /oldroot/run /oldrun

# Unmount all mounts now.
umount "$(mount | awk '$3 ~/^\/oldroot/ {print $3}' | sort -r)"

case "$1" in
  reboot|poweroff|halt) "$1" -f ;;
  *) halt -f;;
esac